[package]
name = "pkgcraft"
version = "0.0.7"
description = "library of Gentoo functionality"
homepage = "https://github.com/pkgcraft/pkgcraft/tree/main/crates/pkgcraft"
repository = "https://github.com/pkgcraft/pkgcraft/tree/main/crates/pkgcraft"
readme = "README.md"
license = "MIT"
autotests = false
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
name = "pkgcraft"
path = "src/lib.rs"

[[bin]]
name = "pk"
bench = false
required-features = ["tools"]

[features]
default = []
# enable git repo syncing support
git = ["dep:git2"]
# enable repo syncing over https, e.g. tar+https
https = ["dep:flate2", "dep:reqwest", "dep:tar", "dep:tokio"]
# build command-line tools
tools = [
	"dep:aho-corasick",
	"dep:anyhow",
	"dep:clap-verbosity-flag",
	"dep:humantime",
	"dep:indicatif",
	"dep:is-terminal",
	"dep:num_cpus",
	"dep:tracing-log",
	"dep:tracing-subscriber",
]
# export test support for integration tests
test = ["dep:assert_cmd"]

[dependencies]
async-trait = "0.1.68"
blake2 = "0.10.6"
blake3 = { version = "1.3.3", features = ["traits-preview"] }
cached = "0.43.0"
camino = { version = "1.1.4", features = ["serde1"] }
chic = "1.2.2"
clap = { version = "4.3.0", features = ["derive"] }
crossbeam-channel = "0.5.8"
digest = "0.10.7"
enum-as-inner = "0.5.1"
filetime = "0.2.21"
flate2 = { version = "1.0.26", optional = true }
futures = "0.3.28"
git2 = { version = "0.17.2", optional = true }
glob = "0.3.1"
hex = "0.4.3"
humantime = { version = "2.1.0", optional = true }
indexmap = { version = "1.9.3", features = ["serde"] }
indoc = "2.0.1"
is_executable = "1.0.1"
itertools = "0.10.5"
md-5 = "0.10.5"
nix = "0.26.2"
num_cpus = { version = "1.15.0", optional = true }
once_cell = "1.17.2"
peg = "0.8.1"
regex = "1.8.3"
reqwest = { version = "0.11.18", default-features = false, features = ["rustls-tls", "stream"], optional = true }
roxmltree = "0.18.0"
rust-ini = "0.19.0"
scallop = { path = "../scallop", version = "0.0.5" }
serde = { version = "1.0.163", features = ["derive"] }
serde_with = { version = "3.0.0", default-features = false, features = ["macros"] }
sha2 = "0.10.6"
strum = { version = "0.24.1", features = ["derive"] }
sys-info = "0.9.1"
tar = { version = "0.4.38", optional = true }
tempfile = "3.5.0"
thiserror = "1.0.40"
tokio = { version = "1.28.2", features = ["full"], optional = true }
toml = "0.7.4"
tracing = "0.1.37"
walkdir = "2.3.3"

# pk dependencies
aho-corasick = { version = "1.0.1", optional = true }
anyhow = { version = "1.0.71", optional = true }
clap-verbosity-flag = { version = "2.0.1", optional = true }
indicatif = { version = "0.17.4", optional = true }
is-terminal = { version = "0.4.7", optional = true }
tracing-log = { version = "0.1.3", optional = true }
tracing-subscriber = { version = "0.3.17", optional = true }

# test feature dependencies
assert_cmd = { version = "2.0.11", optional = true }

[dev-dependencies]
assert_cmd = "2.0.11"
criterion = "0.5"
ctor = "0.2.2"
maplit = "1.0.2"
predicates = "3.0.3"
tracing-test = "0.2.4"

[[bench]]
name = "bench"
harness = false

[[test]]
name = "pk"
path = "tests/pk/pk.rs"
